### ISSUE TITLE
Question : Linux support planned?

### ISSUE THREAD

**Issue by oscarbg** [NVIDIAGameWorks/Path-Tracing-SDK#1]
Hi,
Congrats for first public release!!
Seeing all tech should be supported on Linux already (dlss,vulkan,ser,etc..) would be nice if Linux support can be added soon..
Edit: seems Streamline 2.0 is still Win only(https://github.com/NVIDIAGameWorks/Streamline/issues/11), anyway Linux support minus the Streamline DLSS support would be still nice to have..

Thanks..

**Comment by fstrugar-nv** [comment]
Hi, thanks! Linux support is on the roadmap although I don't have any specifics yet. I'll leave the task open and update when we have more detail.
