### ISSUE TITLE
The BibTex entry

### ISSUE THREAD

**Issue by bipul-mohanto** [NVIDIAGameWorks/Path-Tracing-SDK#20]
Is there any plan to add a BibTex entry like Falcor did?

**Comment by tiont** [comment]
Hi @bipul-mohanto. Yes, we have a recommended BibText entry which I have provided below. In addition we will add this to the readme in our next update. Thank you!

@online{PTSDK,
                title = {{{NVIDIA}}\textregistered{} {Path Tracing SDK}},
                author = {{NVIDIA}},
                year = 2023,
                url = {https://github.com/NVIDIAGameWorks/Path-Tracing-SDK},
                urldate = {2024-01-26},
}
