### ISSUE TITLE
update_dependencies.bat is missing

### ISSUE THREAD

**Issue by TheMostDiligent** [NVIDIAGameWorks/Path-Tracing-SDK#21]
The second step of [the build instructions](https://github.com/NVIDIAGameWorks/Path-Tracing-SDK?tab=readme-ov-file#build) suggests to run the `update_dependencies.bat` script, but it is not in the repository.

**Comment by tiont** [comment]
Hi @TheMostDiligent . Thank you for bringing this to our attention. This has been addressed in the most recent SDK update to v1.3. The readme's build instructions have been updated.
