### ISSUE TITLE
[Question] Is there a integration guide of this SDK?

### ISSUE THREAD

**Issue by trsh** [NVIDIAGameWorks/Path-Tracing-SDK#23]
Since its a SDK, I assume I should be able to adopt it to my own engine if its powered by dx or vk. Or maybe this SDK has different purpose?

However I don't see a guide for that and the 3k line sample project is rather overwhelming, or maybe its as short and simple as it can get?

**Comment by tiont** [comment]
Hi @trsh. Currently, the Path Tracing SDK is intended to provide an example of how to leverage a collection of our technologies to implement a real-time path tracer in your engine. The SDK is primarily a sample app to demonstrate a model path tracer and not intended to be a drop-in solution to an existing engine. This, we don't have an integration guide at this time. 

With that said, we are working to expand the documentation and usability of the SDK in the future so please stay tuned.

**Comment by trsh** [comment]
I will. Thank you @tiont for the response.
