### ISSUE TITLE
Enable SER cause performance drop.

### ISSUE THREAD

**Issue by edisonchan** [NVIDIAGameWorks/Path-Tracing-SDK#4]
Scene: timemachnine
GPU: RTX 6000 Ada w/531.18 on windows 11 pro, 3840x2160 120Hz.

enable SER(default setting): 17.4 fps(slow down from about 18fps)
disable SER: about 20fps.

**Comment by fstrugar-nv** [comment]
Hi! Thanks for the report - yeah, 'Transparent Machines' is a glass jaw use case for SER where the whole scene is basically single material, single model, no textures, etc. In this case there is no branch or data divergence and sorting provides no benefit so what you see is the sorting overhead.

There is however an unrelated change planned that should reduce this overhead, so I will leave this issue open until that task is done!
