### ISSUE TITLE
DXR 1.0 or 1.1 is required?

### ISSUE THREAD

**Issue by ohmaya** [NVIDIAGameWorks/Path-Tracing-SDK#5]
https://developer.nvidia.com/rtx/path-tracing/get-started
"DirectX® Raytracing **1.0** API"
https://github.com/NVIDIAGameWorks/Path-Tracing-SDK
"DirectX Raytracing **1.1** API"

There are 2 macros:
- USE_TRACE_RAY_INLINE: Not used.
- USE_RAY_QUERY: Control 1 instance of TraceRayInline and several shader entry functions, but not used in PathTracerBridgeDonut.hlsli.

Thanks.

**Comment by fstrugar-nv** [comment]
Hi! DXR 1.1 is required, it looks like the info on https://developer.nvidia.com/rtx/path-tracing/get-started is incorrect - thank you for noticing, we'll fix it.

**Comment by ohmaya** [comment]
Hi @fstrugar-nv, thanks.

USE_RAY_QUERY is used in several places. Is it possile to switch to a pure DXR 1.0 implementation?

**Comment by fstrugar-nv** [comment]
It's certainly possible but is slightly less efficient for shadow rays and would require using raygen shaders instead of compute shaders for certain passes. This would make the code sample more complex so we have no plans on doing it - but it's possible!
