### ISSUE TITLE
Failed to grow a descriptor heap Error

### ISSUE THREAD

**Issue by tomdrinKEENSWH** [NVIDIAGameWorks/Path-Tracing-SDK#6]
Hello,
I have encountered a error when I was trying to import the Sponza scene from https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Sponza.

![image](https://user-images.githubusercontent.com/79200426/232719345-b7c1009e-4c0c-4066-ae91-92484c39eb8f.png)

The scene can be found here:
https://drive.google.com/file/d/1UuZ27vNjMg96ggvzMCRUIEVTHSv33kMQ/view?usp=share_link

Would it be possible to improve error logging in a way that would hint what is wrong with the scene (if the problem is in the scene)?

**Comment by tomdrinKEENSWH** [comment]
I have found out the issue is caused when a scene contain materials with alphaMode: "MASK".

**Comment by fstrugar-nv** [comment]
https://github.com/nv-jdeligiannis-s fix is now up with v1.1.0 so this is fixed :)
